{
    'sources':
    [
        'MonsterController.cpp',
        'MonsterController.hpp',
        'Player.cpp',
        'Player.hpp',
        'WildlifeController.cpp',
        'WildlifeController.hpp',
    ],
}
