#include "DwarfNameGenerator.hpp"

#include "Random.hpp"

#include "Characters/GameCharacters.hpp"

namespace Dwarf
{
    namespace Character
    {
        typedef std::vector<std::string> NameOptionVector;
        typedef std::pair<NameOptionVector, NameOptionVector> NameOptionPair;
        typedef std::map<std::string, NameOptionPair> NameOptionMap;

        static const NameOptionPair DwarfNameOptions =
        {
            {
                "A",
                "An",
                "Ar",
                "Az",
                "B",
                "Bel",
                "Bar",
                "Baz",
                "Bof",
                "Bol",
                "D",
                "Dar",
                "Del",
                "Dol",
                "Dor",
                "Dw",
                "Duer",
                "Dur",
                "El",
                "Er",
                "Fal",
                "Far",
                "Gar",
                "Gil",
                "Gim",
                "Glan",
                "Glor",
                "Har",
                "Jar",
                "Kil",
                "Ma",
                "Mor",
                "Nal",
                "Nor",
                "Nur",
                "O",
                "Or",
                "Ov",
                "Rei",
                "Th",
                "Tho",
                "Thr",
                "Tor",
                "Ur",
                "Val",
                "Von",
                "Whur",
                "Wer",
                "Yur",
            },
            {
                "im",
                "ain",
                "ak",
                "ar",
                "auk",
                "bere",
                "bir",
                "dak",
                "dal",
                "din",
                "el",
                "ent",
                "erl",
                "gal",
                "gar",
                "gan",
                "gen",
                "grim",
                "gur",
                "ias",
                "i",
                "ili",
                "im",
                "in",
                "ir",
                "kas",
                "kral",
                "lond",
                "o",
                "on",
                "or",
                "oril",
                "rak",
                "ral",
                "ric",
                "rid",
                "rim",
                "ring",
                "ster",
                "sun",
                "ten",
                "thal",
                "then",
                "thic",
                "thur",
                "ut",
                "ur",
                "urt",
                "val",
                "var",
            },
        };

        static const NameOptionVector DwarfEnemyTypeNames =
        {
            "Ork",
            "Goblin",
            "Gnome",
            "Ghost",
            "Ghoul",
            "Vampire",
            "Skeleton",
            "Ogre",
            "Lich",
        };

        static const NameOptionMap& DwarfClassNameOptions()
        {
            static const NameOptionMap map
            {
                {
                    Dwarves::Brewer(),
                    {
                        {
                            "Lager",
                            "Potion",
                            "Stout",
                            "Malt",
                            "Beverage",
                            "Ale",
                            "Beer",
                            "Draft",
                        },
                        {
                            "blender",
                            "brewer",
                            "drinker",
                            "gulper",
                            "infuser",
                            "chugger",
                            "preper",
                            "funneler",
                            "concocter",
                            "distiller",
                            "chiller",
                            "fermenter",
                            "pasturizer",
                            "pitcher",
                        },
                    }
                },
                {
                    Dwarves::Builder(),
                    {
                        {
                            "Wood",
                            "Iron",
                            "Steel",
                            "Oak",
                            "Maple",
                            "Birch",
                            "Tin",
                            "Copper",
                            "Bronze",
                            "Lead",
                            "Mithril",
                            "Zinc",
                            "Cobalt",
                        },
                        {
                            "builder",
                            "binder",
                            "baluster",
                            "bonder",
                            "bracer",
                            "raiser",
                            "constructor",
                            "deconstructor",
                            "molder",
                            "sculpter",
                        },
                    },
                },
                {
                    Dwarves::Cook(),
                    {
                        DwarfEnemyTypeNames,
                        {
                            "cooker",
                            "sauter",
                            "flamber",
                            "roaster",
                            "fryer",
                            "baker",
                            "broiler",
                            "blancher",
                            "baster",
                            "griller",
                            "marinater",
                            "stewer",
                            "steamer",
                        },
                    },
                },
                {
                    Dwarves::Fighter(),
                    {
                        DwarfEnemyTypeNames,
                        {
                            "basher",
                            "boxer",
                            "choker",
                            "mauler",
                            "beater",
                            "grappler",
                            "slapper",
                            "pummeler",
                            "striker",
                            "lasher",
                            "thumper",
                            "puncher",
                            "stabber",
                            "jabber",
                            "thrower",
                            "assaulter",
                            "uppercutter",
                            "overwhelmer",
                            "render",
                            "eveicerator",
                            "assassinator",
                            "disembowler",
                            "garroter",
                            "cutter",
                            "hunter",
                            "hater",
                        },
                    },
                },
                {
                    Dwarves::Navigator(),
                    {
                        {
                            "Crypt",
                            "Tomb",
                            "Graveyard",
                            "Nook",
                            "Cranny",
                            "Cave",
                            "Fissure",
                            "Hole",
                            "Gorge",
                            "Mausoleum",
                            "Fjord",
                            "Crevice",
                            "Rift",
                            "Cleft",
                            "Cavern",
                            "Den",
                        },
                        {
                            "searcher",
                            "hunter",
                            "grappler",
                            "discoverer",
                            "forager",
                            "mapper",
                            "charter",
                            "explorer",
                            "spelunker",
                            "climber",
                            "locator",
                            "ascender",
                            "descender",
                            "scaler",
                            "rambler",
                            "clamberer",
                        },
                    },
                },
                {
                    Dwarves::Miner(),
                    {
                        {
                            "Gem",
                            "Ruby",
                            "Gold",
                            "Ore",
                            "Silver",
                            "Pyrite",
                            "Diamond",
                            "Crystal",
                            "Sapphire",
                            "Emerald",
                            "Garnet",
                            "Flint",
                            "Chalk",
                            "Quartz",
                            "Slate",
                            "Shale",
                            "Topaz",
                            "Beryl",
                            "Opal",
                        },
                        {
                            "miner",
                            "finder",
                            "picker",
                            "polisher",
                            "sifter",
                            "cutter",
                            "dumper",
                            "hunter",
                            "seeker",
                            "hoister",
                            "coveter",
                            "loader",
                            "lugger",
                            "miller",
                        },
                    },
                },
            };
            return map;
        };

        std::string GenerateDwarfFirstName()
        {
            return Random::RandomItem(DwarfNameOptions.first) + Random::RandomItem(DwarfNameOptions.second);
        }

        std::string GenerateDwarfTitle(const std::string& type)
        {
            assert(DwarfClassNameOptions().find(type) != DwarfClassNameOptions().end());
            const NameOptionPair& options = DwarfClassNameOptions().at(type);
            return Random::RandomItem(options.first) + Random::RandomItem(options.second);
        }

        std::string GenerateDwarfFullName(const std::string& type)
        {
            return GenerateDwarfFirstName() + " " + GenerateDwarfTitle(type);
        }
    }
}
