{
    'sources':
    [
        'BasicArmor.cpp',
        'BasicArmor.hpp',
        'BrewerArmor.cpp',
        'BrewerArmor.hpp',
        'BuilderArmor.cpp',
        'BuilderArmor.hpp',
        'CookArmor.cpp',
        'CookArmor.hpp',
        'FighterArmor.cpp',
        'FighterArmor.hpp',
        'MinerArmor.cpp',
        'MinerArmor.hpp',
        'NavigatorArmor.cpp',
        'NavigatorArmor.hpp',
    ],
    'includes':
    [
    ],
}
