{
    'sources':
    [
        'BrewerDwarf.cpp',
        'BrewerDwarf.hpp',
        'BuilderDwarf.cpp',
        'BuilderDwarf.hpp',
        'CookDwarf.cpp',
        'CookDwarf.hpp',
        'Dwarf.cpp',
        'Dwarf.hpp',
        'Dwarf.inl',
        'FighterDwarf.hpp',
        'FighterDwarf.cpp',
        'MinerDwarf.cpp',
        'MinerDwarf.hpp',
        'NavigatorDwarf.cpp',
        'NavigatorDwarf.hpp',
    ],
}
